### ISSUE TITLE
Incorrect usage of s6-applyuidgid in /etc/s6/services/s6-svscan-log/run?

### ISSUE THREAD

**Issue by robinroestenburg** [just-containers/s6-overlay-builder#24]
Hi,

I found your effort of building this s6-overlay through the thread on supervision mailing list. I have been following it a bit (love it!) and, as a test, am currently migrating my images (based on the Phusion baseimage) to use this overlay.

I know this is work in progress, just wanted to provide some feedback from my tests.

I have some of the images running, but as of the latest build I have some warnings in the docker logs output. I get the following output (when using `S6_USE_CATCHALL_LOGGER` set to 0):

```
$ docker logs clacks
[fix-attrs.d] applying owners & permissions fixes...
[fix-attrs.d] applying 00-runscripts...  exited 0
[fix-attrs.d] applying base_scripts...  exited 0
[fix-attrs.d] applying clacks_scripts...  exited 0
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
s6-applyuidgid: usage: s6-applyuidgid [ -z ] [ -u uid ] [ -g gid ] [ -G gidlist ] [ -U ] prog...
s6-applyuidgid: usage: s6-applyuidgid [ -z ] [ -u uid ] [ -g gid ] [ -G gidlist ] [ -U ] prog...
s6-applyuidgid: usage: s6-applyuidgid [ -z ] [ -u uid ] [ -g gid ] [ -G gidlist ] [ -U ] prog...
```

It seems to be triggered by the `/etc/s6/services/s6-svscan-log/run` script, but the call inside looks OK to me?

**Comment by glerchundi** [comment]
Hi,

Nice to see people is interested in our work!

Which version of the overlay are you using? In the latest one (v1.8.2), the one I've published today this shouldn't happen because:

[`/etc/s6/services/s6-svscan-log/run`](https://github.com/just-containers/s6-overlay-builder/blob/v1.8.2/builder/overlay-rootfs/etc/s6/init-no-catchall/init-stage1) is deleted at the very beginning, in concrete, in the stage1.

Anyway, can you provide me the `Dockerfile` to test it myself and see what's going on?

**Comment by robinroestenburg** [comment]
Yes, I am using v1.8.2.

When I strip my `Dockerfile` down to the bare essentials (only containing S6 overlay and /init command), it works. So, I probably broke something :wink:

I will re-add commands to the `Dockerfile` one at a time to see when it breaks.

**Comment by dreamcat4** [comment]
An FYI, while on the subject of choosing base images:

It seems the best 'all round' official base image right now is `ubuntu-debootstrap:14.04`.

I am switching over to it and recommend it to you guys too. Because that one is the same as official `ubuntu`, but a more minimal image built with `--variant=minbase` option. This makes it significantly smaller than the full ubuntu image (and of course the phusion one too).

It feels more like the `debian` images, but even smaller than debian is (85MB vs 120MB). And you can still use all the same ubuntu PPA 3rd party softwares etc. to install anything that you need.

As it is missing certain utilities (such as dhclient, ifconfig and so on). Which is always a price to pay for a smaller image.

```sh
man debootstrap
…
       --variant=minbase|buildd|fakechroot|scratchbox
              Name  of  the  bootstrap  script variant to use.  Currently, the variants supported are minbase, which only includes
              essential packages and apt;
```

**Comment by robinroestenburg** [comment]
Thanks, I will try it out after I have everything running again.

Meanwhile, I found the problem:

```
cat containers/base/rootfs/etc/services.d/monit/log/run
#!/usr/bin/execlineb -P

s6-setuidgid deployer:deployer
s6-log -bp n10 s10485760 T /var/log/monit
```

It breaks on the `s6-setuidgid` line with previously mentioned `s6-applyuidgid` error. I will investigate further to see why this fails for me.

As it is not an issue with the overlay, I am closing this.

**Comment by glerchundi** [comment]
try this:
```
s6-setuidgid deployer
s6-log -bp n10 s10485760 T /var/log/monit
```

As s6 documentation states (http://skarnet.org/software/s6/s6-setuidgid.html):
* If account contains a colon, it is interpreted as uid:gid, else it is interpreted as a username and looked up by name in the account database.

**Comment by glerchundi** [comment]
@dreamcat4 I didn't know that debootstrap-ubuntu:14.04 even existed, thanks for pointing that out, I'm going to change `just-containers/base` right now!

**Comment by robinroestenburg** [comment]
@glerchundi that was it, thanks :+1:
